#!/bin/bash
# The save directory is not the mount point, and the pieces that keep it so.
#
# A full shard cannot boot in CI: the client art is proprietary and deliberately
# absent, so no save cycle can be observed here. What CAN be proven, without a
# shard, is every piece the fix rests on:
#   the mechanism itself, that a mount point cannot be renamed and a directory
#     inside one can;
#   the init step, on a fresh volume, on the old layout, on both at once, and
#     twice in a row;
#   the health check, against a fresh save, a stale one, none at all, and no
#     process, with the same script production runs;
#   the save-index reader, against a v4 index, a v5 index, and one it should
#     refuse.
# Every negative case is exercised too: a check that has only ever passed has
# not proved it can fail.
#
#   ./tests/e2e-save-layout.sh
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

ALPINE="${MODERNUO_INIT_IMAGE_TAG:-alpine:3.22@sha256:14358309a308569c32bdc37e2e0e9694be33a9d99e68afb0f5ff33cc1f695dce}"
RUNTIME="${MODERNUO_BASE_IMAGE:-mcr.microsoft.com/dotnet/runtime:10.0}"
WORK="$(mktemp -d)"
HC="hc-$$"
PASSED=0; FAILED=0
cleanup() { docker rm -f "$HC" >/dev/null 2>&1; rm -rf "$WORK"; }
trap cleanup EXIT
pass() { echo "  PASS: $1"; PASSED=$((PASSED+1)); }
fail() { echo "  FAIL: $1"; FAILED=$((FAILED+1)); }

# The init container runs with exactly the capability set the compose file
# gives it, so this proves that set is enough on a real host, where the
# directories belong to whoever ran git clone and not to root.
init() {
  docker run --rm --cap-drop ALL --cap-add CHOWN --cap-add DAC_OVERRIDE --cap-add FOWNER \
    -v "$1:/world" -v "$2:/configuration" -v "$PWD/tools/init-save-layout.sh:/init.sh:ro" \
    "$ALPINE" sh /init.sh
}
json_ok() { python3 -c 'import json,sys; json.load(open(sys.argv[1]))' "$1" 2>/dev/null; }
save_path() { python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["settings"]["world.savePath"])' "$1" 2>/dev/null; }

echo "=== the mechanism: a mount point cannot be renamed, a directory inside one can ==="
mkdir -p "$WORK/m1" "$WORK/m2"
if docker run --rm -v "$WORK/m1:/app/Saves" "$ALPINE" sh -c 'mkdir -p /app/Saves.next && mv /app/Saves /app/Saves.prev' >/dev/null 2>&1; then
  fail "renaming the mount point succeeded, so the whole premise is wrong"
else
  pass "with ./data mounted at /app/Saves, the set-aside rename fails (Resource busy)"
fi
if docker run --rm -v "$WORK/m2:/app/World" "$ALPINE" sh -c 'mkdir -p /app/World/Saves /app/World/Saves.next && mv /app/World/Saves /app/World/Saves.prev && mv /app/World/Saves.next /app/World/Saves' >/dev/null 2>&1; then
  pass "with ./data mounted at /app/World, the staged publication completes"
else
  fail "the rename sequence failed even with the mount as the parent"
fi

echo
echo "=== init on a fresh deployment: empty ./data, no config yet ==="
mkdir -p "$WORK/f/data" "$WORK/f/config"
if init "$WORK/f/data" "$WORK/f/config" >/dev/null 2>&1 && [ -d "$WORK/f/data/Saves" ]; then
  pass "Saves/ is created under the mount"
else
  fail "init did not create data/Saves on a fresh volume"
fi
if json_ok "$WORK/f/config/modernuo.json" && [ "$(save_path "$WORK/f/config/modernuo.json")" = "World/Saves" ]; then
  pass "a minimal modernuo.json is written with world.savePath World/Saves, and it is valid JSON"
else
  fail "the fresh configuration is missing, invalid, or points elsewhere"
fi

echo
echo "=== init on the old layout: a world at the root of ./data, config generated by ModernUO ==="
mkdir -p "$WORK/o/data/Items" "$WORK/o/data/Mobiles" "$WORK/o/data/Accounts" "$WORK/o/config"
echo world > "$WORK/o/data/Items/Items.bin"; echo idx > "$WORK/o/data/Items/Items.idx"; echo m > "$WORK/o/data/Mobiles/Mobiles.bin"
cat > "$WORK/o/config/modernuo.json" <<'JSON'
{
  "assemblyDirectories": ["./Assemblies"],
  "dataDirectories": ["/uodata"],
  "listeners": ["0.0.0.0:2593"],
  "settings": {
    "autosave.saveDelay": "00:05:00",
    "serverListing.serverName": "Test Shard",
    "world.savePath": "Saves",
    "world.useMultithreadedSaves": "True"
  }
}
JSON
out="$(init "$WORK/o/data" "$WORK/o/config" 2>&1)"
if [ -f "$WORK/o/data/Saves/Items/Items.bin" ] && [ -f "$WORK/o/data/Saves/Mobiles/Mobiles.bin" ] && [ ! -e "$WORK/o/data/Items" ]; then
  pass "the world moved into data/Saves/ ($(echo "$out" | grep -c '  moved') entries)"
else
  fail "the old-layout world was not moved: $out"
fi
if [ "$(save_path "$WORK/o/config/modernuo.json")" = "World/Saves" ] && json_ok "$WORK/o/config/modernuo.json"; then
  pass "world.savePath rewritten from Saves to World/Saves; the file is still valid JSON"
else
  fail "world.savePath was not rewritten, or the file was damaged"
fi
snap="$(find "$WORK/o" -type f -exec md5sum {} + | sort)"
if init "$WORK/o/data" "$WORK/o/config" >/dev/null 2>&1 && [ "$(find "$WORK/o" -type f -exec md5sum {} + | sort)" = "$snap" ]; then
  pass "a second run changes nothing (idempotent)"
else
  fail "the second run altered files or failed"
fi

echo
echo "=== init refuses when both layouts hold a world ==="
mkdir -p "$WORK/b/data/Items" "$WORK/b/data/Saves/Items" "$WORK/b/config"
echo a > "$WORK/b/data/Items/Items.bin"; echo b > "$WORK/b/data/Saves/Items/Items.bin"
if init "$WORK/b/data" "$WORK/b/config" >/dev/null 2>&1; then
  fail "init guessed which of two worlds was the real one"
else
  if [ -f "$WORK/b/data/Items/Items.bin" ] && [ -f "$WORK/b/data/Saves/Items/Items.bin" ]; then
    pass "two worlds present: init refuses and touches neither"
  else
    fail "init refused but moved something anyway"
  fi
fi

echo
echo "=== init inserts the key when settings exist without it ==="
mkdir -p "$WORK/k/data" "$WORK/k/config"
printf '{\n  "settings": {\n    "serverListing.serverName": "Shard"\n  }\n}\n' > "$WORK/k/config/modernuo.json"
if init "$WORK/k/data" "$WORK/k/config" >/dev/null 2>&1 && json_ok "$WORK/k/config/modernuo.json" && [ "$(save_path "$WORK/k/config/modernuo.json")" = "World/Saves" ]; then
  pass "world.savePath inserted beside existing settings, file still valid JSON"
else
  fail "insertion failed or broke the JSON"
fi
mkdir -p "$WORK/e/data" "$WORK/e/config"
printf '{ "settings": {} }\n' > "$WORK/e/config/modernuo.json"
if init "$WORK/e/data" "$WORK/e/config" >/dev/null 2>&1 && json_ok "$WORK/e/config/modernuo.json" && [ "$(save_path "$WORK/e/config/modernuo.json")" = "World/Saves" ]; then
  pass "an empty settings object gets the key without a trailing comma"
else
  fail "the empty-settings case produced invalid JSON"
fi

echo
echo "=== the health check, the same script production runs, against fake state ==="
docker rm -f "$HC" >/dev/null 2>&1
docker run -d --name "$HC" -v "$PWD/tools/healthcheck.sh:/healthcheck.sh:ro" "$RUNTIME" sh -c 'sleep 3600' /app/ModernUO.dll >/dev/null
sleep 1
hc() { docker exec -e MODERNUO_SAVE_FILE=/tmp/w/Items.bin -e MODERNUO_SAVE_MAX_AGE="${1:-20}" "$HC" sh /healthcheck.sh; }
docker exec "$HC" sh -c 'mkdir -p /tmp/w && touch /tmp/w/Items.bin'
if hc; then pass "process up, save written just now: healthy"; else fail "a fresh save was called unhealthy"; fi
docker exec "$HC" sh -c 'touch -d "30 minutes ago" /tmp/w/Items.bin'
if hc; then fail "a save 30 minutes old passed a 20 minute window"; else pass "process up, save 30 minutes old: unhealthy"; fi
if hc 45; then pass "the window is configurable: 30 minutes old passes a 45 minute window"; else fail "MODERNUO_SAVE_MAX_AGE is not honoured"; fi
docker exec "$HC" sh -c 'rm -f /tmp/w/Items.bin'
if hc; then pass "no save yet on a shard up for seconds: healthy (it is still booting)"; else fail "a young shard with no save was called unhealthy"; fi
if hc 0; then fail "no save on a shard older than the window passed"; else pass "no save once the shard is older than the window: unhealthy"; fi
if docker run --rm -v "$PWD/tools/healthcheck.sh:/healthcheck.sh:ro" "$RUNTIME" sh /healthcheck.sh >/dev/null 2>&1; then
  fail "the health check was green with no ModernUO process at all"
else
  pass "no ModernUO process: unhealthy"
fi

echo
echo "=== the save-index reader, against indexes it has and has not seen ==="
sed -n "/<<'PY'\$/,/^PY\$/p" tools/world-stats.sh | sed '1d;$d' > "$WORK/parser.py"
python3 - "$WORK" <<'PY'
import struct, sys, os
w = sys.argv[1]
def idx(ver, types, count):
    b = struct.pack("<i", ver) + (b"\0" * 8 if ver == 5 else b"") + struct.pack("<i", len(types))
    for t in types:
        e = t.encode(); b += bytes([len(e)]) + e
    return b + struct.pack("<i", count) + b"\0" * 32
for ver in (4, 5, 6):
    d = os.path.join(w, "v%d" % ver); os.makedirs(d, exist_ok=True)
    open(os.path.join(d, "items.idx"), "wb").write(idx(ver, ["Server.Items.Spawner", "Server.Items.Gold"], 174873))
    open(os.path.join(d, "mobs.idx"), "wb").write(idx(ver, ["Server.Mobiles.Banker", "Server.Mobiles.Rat"], 29072))
PY
for ver in 4 5; do
  out="$(python3 "$WORK/parser.py" "$WORK/v$ver/items.idx" "$WORK/v$ver/mobs.idx" 2>&1)"
  if grep -q "items     174873" <<<"$out" && grep -q "mobiles    29072" <<<"$out" && grep -q "Spawner" <<<"$out" && grep -q "decorated and inhabited" <<<"$out"; then
    pass "v$ver index: 174873 items, 29072 mobiles, spawner seen, verdict inhabited"
  else
    fail "v$ver index misread: $(echo "$out" | head -4 | tr '\n' '|')"
  fi
done
if python3 "$WORK/parser.py" "$WORK/v6/items.idx" "$WORK/v6/mobs.idx" >/dev/null 2>&1; then
  fail "an index version the reader does not know was counted anyway"
else
  pass "v6 index: refused rather than guessed"
fi

echo
echo "passed: $PASSED   failed: $FAILED"
[ "$FAILED" -eq 0 ]
